game1/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("pro",views.pro_players,name="pro"),
    path("get_stats",views.players,name="get_stats"),
    # path('verify-stats/', views.verify_stats, name='verify_stats'),
]

stats_api/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('game1/', include(('game1.urls', 'game1'), namespace='game1'))
]

game1/models.py
from django.db import models

# Create your models here.

game1/views.py
from django.shortcuts import render
import requests
from game1.player import Player
import json
from django.http import JsonResponse,HttpResponse
from django.shortcuts import redirect
from django.template.loader import render_to_string
from django.views.decorators.csrf import csrf_exempt

base_url="https://api.opendota.com/api/"
# Create your views here.


def fetch_proof_from_js():
    url = "http://localhost:3000/fetch-proof"
    response = requests.get(url)
    if response.status_code == 200:
        return response.json()
    else:
        return "Error fetching proof from JS."

# def verify_stats(request):
#     if request.method == "GET":
#         proof = fetch_proof_from_js()
#         print(proof)
#         is_verified = True
#         if(proof == "Error fetching proof from JS."):
#             is_verified = False
#         # # Example logic: Replace this with your actual verification logic
#         # is_verified = True  # Example: You can perform checks or calculations here

#         if is_verified:
#             return JsonResponse({'message': 'Player stats are verified.'})
#         else:
#             return JsonResponse({'message': 'Verification failed. Player stats are invalid.'})
#     return JsonResponse({'message': 'Invalid request method.'}, status=405)


def players(request):
    account_id=request.GET.get('account_id')
    print(account_id)
    
    proof = fetch_proof_from_js()
    if(proof == "Error fetching proof from JS."):
        print("There was an error generating from of player Data.")
    else:
        print("Proof of player data: ", proof)
    
    specific_attr=request.GET.get('specific_attr')
    if specific_attr:
        player=Player(account_id)
        data={specific_attr:player.fetch_player_data_specific(specific_attr)}
        print(len(data[specific_attr]))
        pages=render_to_string("game1/sections/pages.html",{"total_pages":range(2,5)})
        html=render_to_string('game1/sections/matches.html',data)
        return JsonResponse({'html':html,'pages':pages})
        # return JsonResponse({'specific_attr':player.fetch_player_data_specific(specific_attr)})
    player=Player(account_id)

    return JsonResponse({'stats':player.fetch_player_data()})

# import requests




def pro_players(request):
    endpoint="proPlayers"
    response=requests.get(base_url+endpoint)
    print(response)
    # print(fetch_proof_from_js())
    # print("hello")
    return render(request, "game1/pro_players.html", {"pro_players":response.json()})

def public_matches(request):
    endpoint="publicMatches"
    response=requests.get(base_url+endpoint)
    return response

def pro_matches(request):
    endpoint="proMatches"
    response=requests.get(base_url+endpoint)
    return response

def index(request):
    return render(request, "game1/index.html")

# def fetch_proof_from_js():
#     url = "http://localhost:3000/fetch-proof"
#     response = requests.get(url)
#     if response.status_code == 200:
#         return response.json()
#     else:
#         return "Error fetching proof from JS."

# def verify_stats(request):
#     if request.method == "GET":
#         proof = fetch_proof_from_js()
#         print(proof)
#         is_verified = True
#         if(proof == "Error fetching proof from JS."):
#             is_verified = False
#         # # Example logic: Replace this with your actual verification logic
#         # is_verified = True  # Example: You can perform checks or calculations here

#         if is_verified:
#             return JsonResponse({'message': 'Player stats are verified.'})
#         else:
#             return JsonResponse({'message': 'Verification failed. Player stats are invalid.'})
#     return JsonResponse({'message': 'Invalid request method.'}, status=405)

game1/templates/game1/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Game Tracker</title>
  {% block styles %}
  {% endblock %}
</head>
<body>
  <header>
    <div class="logo">Game Tracker</div>
    <nav>
      <ul>
        <li><a href="{% url 'game1:index' %}">Home</a></li>
        <li><a href="{% url 'game1:pro' %}">Pro Players</a></li>
        <li><a href="#">Stats</a></li>
        <li><a href="#">About</a></li>
      </ul>
    </nav>
  </header>
  <main>
    {% block content %}{% endblock %}
  </main>

  <footer>
    <p>&copy; 2025 Game Tracker. All Rights Reserved.</p>
  </footer>
  {% block scripts %}
  {% endblock %}
</body>
</html>

game1/templates/game1/index.html
{% extends 'game1/base.html' %}
{% load static %}
{% block styles %}
    <link rel="stylesheet" href="{% static 'game1/styles.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet">
{% endblock %}
{% block content %}
    <section class="search-section">
      <h1>Track Your Game Stats</h1>
      <input type="text" id="player-name" placeholder="Enter Account Id">
      <button id="search-btn">Search and generate ZKP
      </button>
    </section>
    
    <section class="stats-section" id="stats-section">
      <h2>Player Stats</h2>
      <div id="stats-container">
        {% csrf_token %}
        <p>Enter a player name to see their stats.</p>
        <button id="verify-stats-btn" class="btn btn-primary mt-3">Verify Stats</button>
        <div id="verification-result" class="mt-3"></div>
        <div class="profile-container">
          <div class="profile-header">
            <img src="{{player.avatar}}" alt="Avatar" id="avatar">
            <div>
              <h1 id="personaname">{{player.personaname}}</h1>
              <a href="#" target="_blank" id="profilelink">View Profile</a>
            </div>
          </div>
          <div class="navigation">
            <a href="#overview">Overview</a>
            <a href="#matches">Matches</a>
            <a href="#performance">Performance</a>
            <a href="#agents">Agents</a>
            <a href="#maps">Maps</a>
            <a href="#weapons">Weapons</a>
            <a href="#customs">Customs</a>
            <a href="#crosshairs">Crosshairs</a>
            <a href="#lineups">Lineups</a>
          </div>
          <div id="overview" class="section">
            <h2>Section 1</h2>
            <div class="profile-details">
              <div><strong>Account ID:</strong>{{player.account_id}}</div>
              <div><strong>Steam ID:</strong> {{player.steamid}}</div>
              <div><strong>Last Login:</strong>{{player.last_login}}</div>
              <div><strong>Full History Time:</strong>{{player.full_history_time}}</div>
              <div><strong>Last Match Time:</strong> {{player.last_match_time}}</div>
              <div><strong>Country Code:</strong>{{player.loccountrycode}}</div>
              <div><strong>Team Name:</strong>{{player.team_name}}</div>
              <div><strong>Team Tag:</strong>{{player.team_tag}}</div>
              <div><strong>Fantasy Role:</strong>{{player.fantasy_role}}</div>
              <div><strong>Pro Player:</strong>{{player.is_pro}}</div>
              <div><strong>Plus Member:</strong>{{player.plus}}</div>
            </div>
          </div>
          <div id="matches" class="section">
            <div class="match-history">
            <div class="match-header">Match History</div>
            <ul id="matches-list"></ul>
            <div class="container mt-4">
              <nav aria-label="Page navigation example">
                  <ul class="pagination">
                  </ul>
              </nav>
            </div>
          </div>
          </div>
          <div id="section3" class="section">
              <h2>Section 3</h2>
              <p>This is the content of Section 3.</p>
        </div>
      </div>
      </div>
    </section>
{% endblock %}

{% block scripts %}
    <script type="text/javascript" src="https://code.jquery.com/jquery-1.7.1.min.js"></script>
    <script src="{% static 'game1/scripts.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"></script>
    {% comment %} <script>
      document.getElementById('verify-stats-btn').addEventListener('click', function () {
        fetch("{% url 'verify_stats' %}")
          .then(response => response.json())
          .then(data => {
            // Display the response in the 'verification-result' div
            document.getElementById('verification-result').textContent = data.message;
          })
          .catch(error => {
            document.getElementById('verification-result').textContent = "An error occurred.";
            console.error('Error:', error);
          });
      });
    </script> {% endcomment %}
    
{% endblock %}

game1/templates/game1/pro_players.html
{% extends 'game1/base.html' %}
{% load static %}

{% block styles %}
  <link rel="stylesheet" href="{% static 'game1/pro_player.css' %}">
{% endblock %}
{% block content %}
    <h2>Pro Players</h2>
    {% for player in pro_players %}
    <ul id="pro-players-list">
      <li>
        <div class="profile-container">
          <div class="profile-header">
              <img src="{{player.avatar}}" alt="Avatar">
              <div>
                  <h1>{{player.personaname}}</h1>
                  <a href="https://steamcommunity.com/id/Newsham/" target="_blank">View Profile</a>
              </div>
          </div>
          <div class="profile-details">
              <div><strong>Account ID:</strong>{{player.account_id}}</div>
              <div><strong>Steam ID:</strong> {{player.steamid}}</div>
              <div><strong>Last Login:</strong>{{player.last_login}}</div>
              <div><strong>Full History Time:</strong>{{player.full_history_time}}</div>
              <div><strong>Last Match Time:</strong> {{player.last_match_time}}</div>
              <div><strong>Country Code:</strong>{{player.loccountrycode}}</div>
              <div><strong>Team Name:</strong>{{player.team_name}}</div>
              <div><strong>Team Tag:</strong>{{player.team_tag}}</div>
              <div><strong>Fantasy Role:</strong>{{player.fantasy_role}}</div>
              <div><strong>Pro Player:</strong>{{player.is_pro}}</div>
              <div><strong>Plus Member:</strong>{{player.plus}}</div>
          </div>
        </div>
      </li>
    </ul>
    {% endfor %}
{% endblock %}

game1/templates/game1/sections/matches.html
<table class="match-list-item">
{% for match in matches %}
     <tr class="match">
        <td>
            <div class="date">{{match.start_time}}</div>
        </td>
        <td>
            <div class="agent">
                <img src="agent1.png" alt="Agent">
            </div>
        </td>
        <td>
            <div class="score {{match.color}}" style="width: 230px;">{{match.radiant_score}}-{{match.dire_score}}</div>
        </td>
        <td>
            <div class="details" style="width: 80px;">
                <div>K/D/A</div>
                <div>{{match.kills}} / {{match.deaths}} / {{match.assists}}</div>
            </div>
        </td>
            
        <td>
            <div class="stat-values">
            <div>K/D</div>
            <div>{{match.kd}}</div>
            </div>
        </td>
        <td>
            <div class="stat-values">
                <div>GPM</div>
                <div>{{match.gold_per_min}}</div>
            </div>
            
        </td>
        <td>
            <div class="stat-values">
                <div>XPM</div>
                <div>{{match.xp_per_min}}</div>
            </div>
        </td>
        <td>
            <div class="stat-values">
                <div>Heal</div>
                <div>{{match.hero_healing}}</div>
            </div>
            
        </td>
        <td>
            <div class="stat-values">
                <div>HD</div>
                <div>{{match.hero_damage}}</div>
            </div>

        </td>
        <td >
            <div class="stat-values">
                <div>TD</div>
                <div>{{match.tower_damage}}</div>
            </div>
        </td>
    </tr>
{% endfor %}
</table>

game1/templates/game1/sections/pages.html
<li class="page-item disabled">
    <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Previous</a>
</li>
<li class="page-item active" aria-current="page"><a class="page-link" href="#">1</a></li>
{% for i in total_pages %}
<li class="page-item"><a class="page-link" href="#">{{i}}</a></li>
{% endfor %}
<li class="page-item"><a class="page-link" href="#">Next</a></li>